/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR                0x40023800UL
#define RCC_CFGR_REG_OFFSET          0x08UL
#define RCC_CFGR_REG_ADDR            (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

// Đã thêm: Định nghĩa chuẩn xác độ dời địa chỉ cho thanh ghi bật nguồn
#define RCC_AHB1ENR_OFFSET           0x30UL
#define RCC_AHB1ENR_ADDR             (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)

#define GPIOA_BASE_ADDR              0x40020000UL

int main(void)
{
    uint32_t *pRccCfgrReg = (uint32_t *) RCC_CFGR_REG_ADDR;

    // 1. Xóa các vị trí bit 21 và 22 để chọn tín hiệu nội bộ làm nguồn xuất ra
    *pRccCfgrReg  &= ~(0x3 << 21);

    // 2. Cấu hình bộ chia tần số (Đặt giá trị chia 4)
    *pRccCfgrReg |= (1 << 25);
    *pRccCfgrReg |= (1 << 26);

    // a) Bật nguồn xung nhịp cho cổng A (ĐÃ SỬA LỖI TÍNH SAI ĐỊA CHỈ Ở ĐÂY)
    uint32_t *pRccAhb1Enr = (uint32_t *) RCC_AHB1ENR_ADDR;
    *pRccAhb1Enr |= (1 << 0); // Đặt vị trí bit số 0 lên mức 1

    // b) Cấu hình chân số 8 của cổng A sang chế độ chức năng thay thế
    uint32_t *pGPIOAModeReg = (uint32_t *)(GPIOA_BASE_ADDR + 0x00);
    *pGPIOAModeReg &= ~(0x3 << 16); // Xóa sạch dữ liệu cũ
    *pGPIOAModeReg |= (0x2 << 16);  // Đặt giá trị nhị phân 10 để kích hoạt

    // c) Cấu hình thanh ghi chức năng thay thế nửa trên để nối tín hiệu ra chân số 8
    uint32_t *pGPIOAAltFunHighReg = (uint32_t *)(GPIOA_BASE_ADDR + 0x24);
    *pGPIOAAltFunHighReg &= ~(0xF << 0); // Xóa 4 vị trí bit đầu tiên về 0

    /* Vòng lặp vô tận để duy trì hoạt động của hệ thống */
    for(;;);
}
