/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR                   0x40023800UL
#define RCC_CR_REG_OFFSET               0x00UL
#define RCC_CFGR_REG_OFFSET             0x08UL
#define RCC_CFGR_REG_ADDR               (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)
#define RCC_CR_REG_ADDR                 (RCC_BASE_ADDR + RCC_CR_REG_OFFSET)
#define GPIOA_BASE_ADDR                 0x40020000UL

// Thêm định nghĩa cho thanh ghi cấp nguồn để mã lệnh gọn gàng, tránh sai sót
#define RCC_AHB1ENR_OFFSET              0x30UL
#define RCC_AHB1ENR_ADDR                (RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)

int main(void) {

    uint32_t *pRccCfgrReg = (uint32_t*) RCC_CFGR_REG_ADDR;
    uint32_t *pRccCrReg = (uint32_t*) RCC_CR_REG_ADDR;

    // 1. Bật nguồn dao động thạch anh ngoài (bit số 16)
    *pRccCrReg |= (1 << 16);

    // 2. Chờ cho đến khi dao động thạch anh bên ngoài ổn định (kiểm tra bit 17)
    while (!(*pRccCrReg & (1 << 17)));

    // 3. Chuyển đổi nhịp tim hệ thống sang nguồn thạch anh ngoài (bit 0 và 1)
    *pRccCfgrReg &= ~(0x3 << 0); // Xóa sạch 2 bit 0 và 1
    *pRccCfgrReg |= (1 << 0);    // Đặt bit 0 lên mức 1

    /* ===================== CẤU HÌNH ĐẦU RA MCO1 ===================== */

    // 1. Chọn dao động thạch anh ngoài làm nguồn xuất ra (bit 21 và 22)
    *pRccCfgrReg &= ~(0x3 << 21); // BƯỚC XÓA: Xóa sạch cả bit 21 và 22
    *pRccCfgrReg |= (0x2 << 21);  // BƯỚC ĐẶT: Ghi giá trị nhị phân 10 vào cụm bit này

    // Cấu hình bộ chia tần số là chia 4 (bit 24, 25, 26 mang giá trị nhị phân 110)
    *pRccCfgrReg &= ~(0x7 << 24); // BƯỚC XÓA: Xóa sạch cụm 3 bit
    *pRccCfgrReg |= (0x6 << 24);  // BƯỚC ĐẶT: Ghi giá trị nhị phân 110 vào cụm bit này

    // 2. Cấu hình chân số 8 cổng A thành chế độ chức năng thay thế

    // a) Cấp nguồn cho bộ phận điều khiển cổng A
    uint32_t *pRCCAhb1Enr = (uint32_t*) RCC_AHB1ENR_ADDR;
    *pRCCAhb1Enr |= (1 << 0);

    // b) Chuyển chân số 8 cổng A sang chế độ chức năng thay thế
    uint32_t *pGPIOAModeReg = (uint32_t*) (GPIOA_BASE_ADDR + 0x00);
    *pGPIOAModeReg &= ~(0x3 << 16); // Xóa sạch dữ liệu cũ
    *pGPIOAModeReg |= (0x2 << 16);  // Ghi giá trị kích hoạt chế độ mới

    // c) Khai báo chọn luồng tín hiệu MCO1 ra chân số 8
    uint32_t *pGPIOAAltFunHighReg = (uint32_t*) (GPIOA_BASE_ADDR + 0x24);
    *pGPIOAAltFunHighReg &= ~(0xF << 0); // Xóa sạch 4 bit đầu tiên về mức 0

    /* Vòng lặp duy trì hệ thống */
    for (;;);
}
